id: P010420
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17112
  title: སྡོམ་པ་གསུམ་རྣམ་པར་ངེས་པ།
  author: ''
  volumes:
    4993be90aafc4ee8ab476dcf56d004b8:
      image_group_id: I8LS17121
      title: ''
      volume_number: 1
      total_pages: 608
